package com.example.xiaojun.kotlin_try.data.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.xiaojun.kotlin_try.data.db.SongAndSheetBean;
import com.example.xiaojun.kotlin_try.data.db.SongInfoBean;
import com.example.xiaojun.kotlin_try.data.db.SongSheetBean;

import com.example.xiaojun.kotlin_try.data.db.SongAndSheetBeanDao;
import com.example.xiaojun.kotlin_try.data.db.SongInfoBeanDao;
import com.example.xiaojun.kotlin_try.data.db.SongSheetBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig songAndSheetBeanDaoConfig;
    private final DaoConfig songInfoBeanDaoConfig;
    private final DaoConfig songSheetBeanDaoConfig;

    private final SongAndSheetBeanDao songAndSheetBeanDao;
    private final SongInfoBeanDao songInfoBeanDao;
    private final SongSheetBeanDao songSheetBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        songAndSheetBeanDaoConfig = daoConfigMap.get(SongAndSheetBeanDao.class).clone();
        songAndSheetBeanDaoConfig.initIdentityScope(type);

        songInfoBeanDaoConfig = daoConfigMap.get(SongInfoBeanDao.class).clone();
        songInfoBeanDaoConfig.initIdentityScope(type);

        songSheetBeanDaoConfig = daoConfigMap.get(SongSheetBeanDao.class).clone();
        songSheetBeanDaoConfig.initIdentityScope(type);

        songAndSheetBeanDao = new SongAndSheetBeanDao(songAndSheetBeanDaoConfig, this);
        songInfoBeanDao = new SongInfoBeanDao(songInfoBeanDaoConfig, this);
        songSheetBeanDao = new SongSheetBeanDao(songSheetBeanDaoConfig, this);

        registerDao(SongAndSheetBean.class, songAndSheetBeanDao);
        registerDao(SongInfoBean.class, songInfoBeanDao);
        registerDao(SongSheetBean.class, songSheetBeanDao);
    }
    
    public void clear() {
        songAndSheetBeanDaoConfig.clearIdentityScope();
        songInfoBeanDaoConfig.clearIdentityScope();
        songSheetBeanDaoConfig.clearIdentityScope();
    }

    public SongAndSheetBeanDao getSongAndSheetBeanDao() {
        return songAndSheetBeanDao;
    }

    public SongInfoBeanDao getSongInfoBeanDao() {
        return songInfoBeanDao;
    }

    public SongSheetBeanDao getSongSheetBeanDao() {
        return songSheetBeanDao;
    }

}
