package com.example.xiaojun.kotlin_try.data.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SONG_AND_SHEET_BEAN".
*/
public class SongAndSheetBeanDao extends AbstractDao<SongAndSheetBean, Long> {

    public static final String TABLENAME = "SONG_AND_SHEET_BEAN";

    /**
     * Properties of entity SongAndSheetBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property SongId = new Property(1, Long.class, "songId", false, "SONG_ID");
        public final static Property SheetId = new Property(2, Long.class, "sheetId", false, "SHEET_ID");
    }


    public SongAndSheetBeanDao(DaoConfig config) {
        super(config);
    }
    
    public SongAndSheetBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SONG_AND_SHEET_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: Id
                "\"SONG_ID\" INTEGER," + // 1: songId
                "\"SHEET_ID\" INTEGER);"); // 2: sheetId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SONG_AND_SHEET_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SongAndSheetBean entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        Long songId = entity.getSongId();
        if (songId != null) {
            stmt.bindLong(2, songId);
        }
 
        Long sheetId = entity.getSheetId();
        if (sheetId != null) {
            stmt.bindLong(3, sheetId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SongAndSheetBean entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        Long songId = entity.getSongId();
        if (songId != null) {
            stmt.bindLong(2, songId);
        }
 
        Long sheetId = entity.getSheetId();
        if (sheetId != null) {
            stmt.bindLong(3, sheetId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SongAndSheetBean readEntity(Cursor cursor, int offset) {
        SongAndSheetBean entity = new SongAndSheetBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // songId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // sheetId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SongAndSheetBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSongId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setSheetId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SongAndSheetBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SongAndSheetBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SongAndSheetBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
